# -*- coding: utf-8 -*-
"""pizza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wax_sKFuJZ4cSXDi41naEW4SyMcHPf2d
"""

# -*- coding: utf-8 -*-
class Pizza:
    def __init__(self, name: str, icon: str,
                 ingredients: list, size: str = 'L'):
        '''
        реализуем класс пицца, от которого будут наследовать
        в этой функции инициализируем основные параметры:
        - имя
        - иконка (для привлечения)
        - ингредиенты (самое главное - начинка нашей пиццы)
        - размер (в этом случае имеет значение)
        '''
        self.name = name
        self.icon = icon
        self.ingredients = ingredients
        self.size = size

    def dict(self):
        '''
        все необходимые параметры закинем в словарь
        '''

        return {'name': self.name,
                'icon': self.icon,
                'ingredients': self.ingredients,
                'size': self.size}

    def __eq__(self, other):
        '''
        тут сравниваем пиццы по разным параметрам
        '''
        return (
            self.name == other.name
            and self.ingredients == other.ingredients
            and self.size == other.size
            )


class Margherita(Pizza):
    def __init__(self, size: str = 'L'):
        super().__init__(
            'Margherita',
            '🧀',
            ['tomato sauce', 'mozzarella', 'tomatoes'],
            size
            )


class Pepperoni(Pizza):
    def __init__(self, size: str = 'L'):
        super().__init__(
            'Pepperoni',
            '🍕',
            ['tomato sauce', 'mozzarella', 'pepperoni'],
            size
            )


class Hawaiian(Pizza):
    def __init__(self, size: str = 'L'):
        super().__init__(
            'Hawaiian',
            '🍍',
            ['tomato sauce', 'mozzarella', 'chicken', 'pineapples'],
            size
            )


class ChickenBBQ(Pizza):
    def __init__(self, size: str = 'L'):
        super().__init__(
            'Chicken BBQ',
            '🍗',
            ['tomato sauce', 'mozzarella', 'chicken', 'BBQ sauce'],
            size
            )



import click
from time import sleep

@click.group()
def cli():
    pass


@cli.command()
@click.option('--size', default='L', type=click.Choice(['L', 'XL']))
@click.option('--delivery', default=False, is_flag=True)
@click.argument('pizza', nargs=1)
def order(pizza: str, size: str, delivery: bool):
    '''
    Готовит и доставляет пиццу
    '''
    pizza_dict = {'margherita': Margherita,
                  'pepperoni': Pepperoni,
                  'hawaiian': Hawaiian,
                  'chickenbbq': ChickenBBQ}
    selected_pizza = pizza_dict[pizza.lower()](size)

    bake(selected_pizza)
    if delivery:
        deliver(selected_pizza)
    else:
        pickup(selected_pizza)


@cli.command()
def menu():
    '''
    Выводит меню
    '''
    pizzas = [Margherita(), Pepperoni(), Hawaiian(), ChickenBBQ()]
    for pizza in pizzas:
        print(f"{pizza.icon} - {pizza.name}: {', '.join(pizza.ingredients)}")


def log(template: str):
    def decorator(func):
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            print(template.format(result))
            return result

        return wrapper

    return decorator


@log('Приготовили за {}с!')
def bake(pizza: Pizza):
    '''
    Готовит пиццу
    '''
    sleep(2)
    return 2


@log('🛵 Доставили за {}с!')
def deliver(pizza: Pizza):
    '''
    Доставляет пиццу
    '''
    sleep(1)
    return 1


@log('🏠 Забрали за {}с!')
def pickup(pizza: Pizza):
    '''
    Самовывоз
    '''
    sleep(1)
    return 1


if __name__ == '__main__':
    cli()