# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wax_sKFuJZ4cSXDi41naEW4SyMcHPf2d
"""

# -*- coding: utf-8 -*-

import unittest
from pizza import Margherita, Pepperoni, Hawaiian, ChickenBBQ, bake, deliver, pickup

class TestPizza(unittest.TestCase):
    def test_pizza_equality(self):
        '''
        Проверяет равенство двух экземпляров одного типа пиццы
        и неравенство экземпляров разных типов пицц
        '''
        self.assertEqual(Margherita(), Margherita())
        self.assertNotEqual(Margherita(), Pepperoni())

    def test_bake(self):
        '''
        Проверяет, что функция bake() возвращает
        правильное значение времени приготовления пиццы
        '''
        pizza = Margherita()
        self.assertEqual(bake(pizza), 2)

    def test_delivery(self):
        '''
        Проверяет, что функция deliver() возвращает
        правильное значение времени доставки пиццы
        '''
        pizza = Margherita()
        self.assertEqual(deliver(pizza), 1)

    def test_pickup(self):
        '''
        Проверяет, что функция pickup() возвращает
        правильное значение времени самовывоза пиццы
        '''
        pizza = Margherita()
        self.assertEqual(pickup(pizza), 1)

    def test_pizza_size_equality(self):
        '''
        сравнение пицц с разными размерами
        '''
        self.assertNotEqual(Margherita('L'), Margherita('XL'))

    def test_pizza_creation(self):
        '''
        Тестирование корректности создания пицц с помощью классов
        '''
        pizza = Margherita()
        self.assertEqual(pizza.name, 'Margherita')
        self.assertEqual(pizza.icon, '🧀')
        self.assertEqual(pizza.ingredients, ['tomato sauce',
                                             'mozzarella', 'tomatoes'])
        self.assertEqual(pizza.size, 'L')

    def test_pizza_dict(self):
        '''
        Тестирование корректности работы функции dict()
        '''
        pizza = Margherita()
        pizza_dict = {'name': 'Margherita',
                      'icon': '🧀',
                      'ingredients': ['tomato sauce', 'mozzarella', 'tomatoes'],
                      'size': 'L'}
        self.assertEqual(pizza.dict(), pizza_dict)

if __name__ == '__main__':
    unittest.main()